package Grafisch;
import Database.DatabaseConnectie;
import java.awt.Color;
import javax.swing.JFrame;

/**
 * De naam en leeftijd van de speler wordt hier ingevuld en vervolgens verwerkt.
 * Verwerken: indien niet in database = nieuwe aanmaken.
 * @author Leander Clappaert
 * @version 31/05/2015
 */
public class PanelIDSolo extends javax.swing.JPanel {
    private final JFrame parentFrame;
    private final DatabaseConnectie db;
    
    /**
     * Creates new form PanelID
     */
    public PanelIDSolo(JFrame frame, DatabaseConnectie db) {
        initComponents();
        this.parentFrame = frame;
        this.db = db;
    }
    
    /**
     * Kijken of de speler reeds bestaat of niet. Indien niet = nieuwe aanmaken.
     */
    private void databaseImplementatie(String naam, int leeftijd) {
        int id = db.checkID(naam, leeftijd);  
        if (id == 0) db.maakNieuweSpelerAan(naam, leeftijd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNaam = new javax.swing.JTextField();
        jLeeftijd = new javax.swing.JTextField();
        jLabelNaam = new javax.swing.JLabel();
        jLabelLeeftijd = new javax.swing.JLabel();
        jValideren = new javax.swing.JButton();
        jLabelIntrotekst = new javax.swing.JLabel();
        jExceptionLabel = new javax.swing.JLabel();
        jBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(580, 310));
        setMinimumSize(new java.awt.Dimension(580, 310));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(580, 310));
        setLayout(null);

        jNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNaamActionPerformed(evt);
            }
        });
        add(jNaam);
        jNaam.setBounds(302, 189, 60, 30);

        jLeeftijd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLeeftijd.setAutoscrolls(false);
        add(jLeeftijd);
        jLeeftijd.setBounds(302, 220, 60, 30);

        jLabelNaam.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNaam.setText("Naam:");
        add(jLabelNaam);
        jLabelNaam.setBounds(237, 192, 60, 14);

        jLabelLeeftijd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLeeftijd.setText("Leeftijd:");
        add(jLabelLeeftijd);
        jLabelLeeftijd.setBounds(237, 223, 60, 14);

        jValideren.setText("VALIDEREN");
        jValideren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValiderenActionPerformed(evt);
            }
        });
        add(jValideren);
        jValideren.setBounds(237, 258, 125, 23);

        jLabelIntrotekst.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIntrotekst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIntrotekst.setText("Hallo! Wat is je naam? Hoe oud ben je?");
        add(jLabelIntrotekst);
        jLabelIntrotekst.setBounds(0, 170, 580, 14);

        jExceptionLabel.setBackground(new java.awt.Color(255, 0, 0));
        jExceptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        jExceptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jExceptionLabel);
        jExceptionLabel.setBounds(372, 220, 208, 20);

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafisch/images/did-a-wheel-of-fortune-contestant-lose-unfairly.jpg"))); // NOI18N
        jBackground.setOpaque(true);
        add(jBackground);
        jBackground.setBounds(0, 0, 580, 310);
    }// </editor-fold>//GEN-END:initComponents
    //Automatisch gegenereerde code die niet te deleten is
    private void jNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNaamActionPerformed

    private void jValiderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValiderenActionPerformed
        String naam = jNaam.getText();
        int leeftijd = 0;
        String test = jLeeftijd.getText(); //via deze weg ontstaat er geen infinite exception loop
        boolean heeftException = false; //dit voorkomt een dubbele error melding: exception + foute leeftijd
        try {
            jExceptionLabel.setOpaque(false);
            leeftijd = Integer.parseInt(test);
        }
        catch (Exception e) {
            heeftException = true;
            jExceptionLabel.setText("Deze waarde is ongeldig!");
            jExceptionLabel.setOpaque(true);
            jExceptionLabel.setBackground(Color.red);
        }
        if (!heeftException && leeftijd < 6) {
            jExceptionLabel.setText("De minimum leeftijd is 6 jaar.");
            jExceptionLabel.setOpaque(true);
            jExceptionLabel.setBackground(Color.red);
        }
        //als alle ingaves geldig zijn:
        else if (!heeftException) {
            jExceptionLabel.setText("");
            jExceptionLabel.setOpaque(false);
            databaseImplementatie(naam, leeftijd);
            parentFrame.setContentPane(new SpelSoloPanel (parentFrame, naam, leeftijd, db));
            parentFrame.validate();
        }
    }//GEN-LAST:event_jValiderenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JLabel jExceptionLabel;
    private javax.swing.JLabel jLabelIntrotekst;
    private javax.swing.JLabel jLabelLeeftijd;
    private javax.swing.JLabel jLabelNaam;
    private javax.swing.JTextField jLeeftijd;
    private javax.swing.JTextField jNaam;
    private javax.swing.JButton jValideren;
    // End of variables declaration//GEN-END:variables
}
