package Grafisch;
import Database.DatabaseConnectie;
import java.awt.Color;
import javax.swing.JFrame;

/**
 * De naam en leeftijd van de spelers worden hier ingevuld en vervolgens verwerkt.
 * Verwerken: indien niet in database = nieuwe aanmaken.
 * @author Leander Clappaert
 * @version 31/05/2015
 */
public class PanelIDTeam extends javax.swing.JPanel {
    private final JFrame parentFrame;
    private final int aantalSpelers; private int i;
    private String[] namen;
    private int[] leeftijden;
    private final DatabaseConnectie db;
    
    /**
     * Creates new form PanelID
     */
    public PanelIDTeam(JFrame frame, int aantalSpelers, DatabaseConnectie db) {
        initComponents();
        this.parentFrame = frame;
        this.aantalSpelers = aantalSpelers;
        this.db = db;
        jLabelIntro.setText("Speler " + (i+1) + ", wat is je naam? Hoe oud ben je?");
        this.i = 0;
        this.namen = new String[aantalSpelers];
        this.leeftijden = new int[aantalSpelers];
    }
    
    /**
     * Kijken of de speler reeds bestaat of niet. Indien niet = nieuwe aanmaken.
     */
    private void databaseImplementatie() {
        int id = db.checkID(namen[i], leeftijden[i]);  
        if (id == 0) db.maakNieuweSpelerAan(namen[i], leeftijden[i]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNaam = new javax.swing.JTextField();
        jLeeftijd = new javax.swing.JTextField();
        jLabelNaam = new javax.swing.JLabel();
        jLabelLeeftijd = new javax.swing.JLabel();
        jValideren = new javax.swing.JButton();
        jLabelIntro = new javax.swing.JLabel();
        jExceptionLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(580, 310));
        setMinimumSize(new java.awt.Dimension(580, 310));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(580, 310));
        setLayout(null);

        jNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNaamActionPerformed(evt);
            }
        });
        add(jNaam);
        jNaam.setBounds(302, 189, 60, 30);

        jLeeftijd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLeeftijd.setAutoscrolls(false);
        add(jLeeftijd);
        jLeeftijd.setBounds(302, 220, 60, 30);

        jLabelNaam.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNaam.setText("Naam:");
        add(jLabelNaam);
        jLabelNaam.setBounds(237, 192, 60, 14);

        jLabelLeeftijd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLeeftijd.setText("Leeftijd:");
        add(jLabelLeeftijd);
        jLabelLeeftijd.setBounds(237, 223, 60, 14);

        jValideren.setText("VALIDEREN");
        jValideren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValiderenActionPerformed(evt);
            }
        });
        add(jValideren);
        jValideren.setBounds(237, 258, 125, 23);

        jLabelIntro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIntro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIntro.setText("IntroTekst");
        add(jLabelIntro);
        jLabelIntro.setBounds(0, 170, 580, 14);

        jExceptionLabel.setBackground(new java.awt.Color(255, 0, 0));
        jExceptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        jExceptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jExceptionLabel);
        jExceptionLabel.setBounds(370, 220, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafisch/images/did-a-wheel-of-fortune-contestant-lose-unfairly.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 310);
    }// </editor-fold>//GEN-END:initComponents

    //Deze methode is automatisch gegenereerd en dus niet te deleten. 
    private void jNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNaamActionPerformed

    /**
     * Gegevens van de speler worden enerzijds doorgegeven en anderzijds vergeleken met de database.
     * Foute inputs worden een groot deel weggewerkt via try catch methode.
     * @param evt button klik
     */
    private void jValiderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValiderenActionPerformed
        namen[i] = jNaam.getText();
        String test = jLeeftijd.getText(); //via deze weg ontstaat er geen infinite exception loop
        boolean heeftException = false; //dit voorkomt een dubbele error melding: exception + foute leeftijd
        try {
            jExceptionLabel.setOpaque(false);
            leeftijden[i] = Integer.parseInt(test);
        }
        catch (Exception e) {
            heeftException = true;
            jExceptionLabel.setText("Deze waarde is ongeldig!");
            jExceptionLabel.setOpaque(true);
            jExceptionLabel.setBackground(Color.red);
        }
        if (!heeftException && leeftijden[i] < 6) {
            jExceptionLabel.setText("De minimum leeftijd is 6 jaar.");
            jExceptionLabel.setOpaque(true);
            jExceptionLabel.setBackground(Color.red);
        }
        //als alle parameters in orde zijn:
        else if (!heeftException && leeftijden[i] >= 6) {
            jExceptionLabel.setText("");
            jExceptionLabel.setOpaque(false);
            databaseImplementatie();
            i++;
            if (i < aantalSpelers) jLabelIntro.setText("Speler " + (i+1) + ", wat is je naam? Hoe oud ben je?");
            else {
                parentFrame.setContentPane(new TeamSpelPanel (parentFrame, namen, leeftijden, aantalSpelers, db));
                parentFrame.validate();
            }
        }
    }//GEN-LAST:event_jValiderenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jExceptionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIntro;
    private javax.swing.JLabel jLabelLeeftijd;
    private javax.swing.JLabel jLabelNaam;
    private javax.swing.JTextField jLeeftijd;
    private javax.swing.JTextField jNaam;
    private javax.swing.JButton jValideren;
    // End of variables declaration//GEN-END:variables
}
