package Grafisch;
import Database.DatabaseConnectie;
import Logica.TeamSpel;
import java.util.Arrays;
import javax.swing.JFrame;

/**
 * Deze panel behoort bij het team spel en geeft enkele statistieken weer van de spelers.
 * @author Leander Clappaert
 * @version 01/06/2015
 */
public class TeamStatsPanel extends javax.swing.JPanel {
    private final JFrame parentFrame;
    private final TeamSpel[] record;
    private final String[] namen;
    private final int[] leeftijden;
    private final DatabaseConnectie db;
    
    /**
     * Creates new form TeamStatsPanel
     */
    public TeamStatsPanel(JFrame frame, String[] namen, int[] leeftijden, TeamSpel[] record, DatabaseConnectie db) {
        initComponents();
        this.parentFrame = frame;
        this.namen = namen;
        this.leeftijden = leeftijden;
        this.record = record;
        this.db = db;
        initialiseerLabels();
        setLabels();
    }
    
    /**
     * Labels worden voor het eerst geïnitialiseerd. 
     */
    public void initialiseerLabels() {
        jWinnaars.setText(" De winnaar(s): ");
        jStats.setText("");
        jWinst.setText("");
    }
    
    /**
     * Checkt wie er gewonnen heeft en wat hun gewonnen saldo is.
     * @return dubbele array met naam, leeftijd en gewonnen saldo van de winnaar
     */
    public String[][] calculateResults() {
        String[][] winnaars = new String[record.length][3];
        int[] results = new int[record.length];
        
        for (int i = 0; i < record.length; i++) {
            results[i] = record[i].getTotaalSaldo();
        }
        Arrays.sort(results);

        //als het bedrag overeenkomt met het grootste bedrag uit dse rij, wordt deze in de winnaarslijst opgenomen
        for (int i = 0; i < record.length; i++) {
            if (results[record.length - 1] == record[i].getTotaalSaldo()) {
                winnaars[i][0] = record[i].getSpelerNaam();
                winnaars[i][1] = "" + record[i].getLeeftijd();
                winnaars[i][2] = "" + record[i].getTotaalSaldo();   
            }
        }
        
        return winnaars;
    }
    
    /**
     * Stelt de labels in van de panel.
     */
    public void setLabels() {
        String[][] winnaars = calculateResults();
        
        for (int i = 0; i < record.length; i++) {           
            jStats.setText
            (
                jStats.getText() + "\n" +
                " Extra info over speler " + record[i].getSpelerNaam() + "\n" +
                "\tTotaal verworven geldsom: " + record[i].getOverallSaldo(db, record[i].getSpelerNaam(), record[i].getLeeftijd()) + ".\n" +
                "\tMax geldsom behaald in 1 spel: " + record[i].getMaxSaldo(db, record[i].getSpelerNaam(), record[i].getLeeftijd()) + "."      
            );            
            jWinst.setText
            (
                jWinst.getText() + "\n" + 
                " " + record[i].getSpelerNaam() + " heeft " + record[i].getTotaalSaldo() + "\n bij dit spel gewonnen.\n"
            );
            if (winnaars[i][0] != null) { //null = speler niet opgenomen geweest in de winnaarslijst
                jWinnaars.setText
                (
                    jWinnaars.getText() + "\n" +
                    "\t" + winnaars[i][0] + "(" + winnaars[i][1] + "): " + winnaars[i][2] + " in de pot."
                );      
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRestart = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jWinnaars = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jStats = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jWinst = new javax.swing.JTextArea();
        jBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(580, 310));
        setMinimumSize(new java.awt.Dimension(580, 310));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(null);

        jButtonRestart.setText("OPNIEUW SPELEN");
        jButtonRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestartActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRestart);
        jButtonRestart.setBounds(20, 10, 170, 30);

        jButtonExit.setText("AFSLUITEN");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExit);
        jButtonExit.setBounds(20, 43, 170, 30);

        add(jPanel1);
        jPanel1.setBounds(370, 0, 210, 80);

        jScrollPane4.setBackground(new java.awt.Color(102, 255, 204));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jWinnaars.setBackground(new java.awt.Color(0, 204, 153));
        jWinnaars.setColumns(20);
        jWinnaars.setForeground(new java.awt.Color(255, 255, 255));
        jWinnaars.setRows(5);
        jWinnaars.setText("De winnaar(s):\n\tJan(8): 10000 euro in pot.\n\tJan(8): 10000 euro in pot.\n\tJan(8): 10000 euro in pot.");
        jWinnaars.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane4.setViewportView(jWinnaars);

        add(jScrollPane4);
        jScrollPane4.setBounds(0, 0, 370, 80);

        jScrollPane2.setBackground(new java.awt.Color(102, 255, 204));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jStats.setBackground(new java.awt.Color(102, 255, 204));
        jStats.setColumns(20);
        jStats.setRows(5);
        jStats.setText("Extra info over speler Jan:\n\tTotaal verworven geldsom: 14500\n\tMax geldosm behaald in 1 spel: 10000\nExtra info over speler Jan:\n\tTotaal verworven geldsom: 14500\n\tMax geldosm behaald in 1 spel: 10000\nExtra info over speler Jan:\n\tTotaal verworven geldsom: 14500\n\tMax geldosm behaald in 1 spel: 10000\nExtra info over speler Jan:\n\tTotaal verworven geldsom: 14500\n\tMax geldosm behaald in 1 spel: 10000");
        jStats.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane2.setViewportView(jStats);

        add(jScrollPane2);
        jScrollPane2.setBounds(210, 80, 370, 230);

        jScrollPane1.setBackground(new java.awt.Color(102, 255, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jWinst.setBackground(new java.awt.Color(102, 255, 204));
        jWinst.setColumns(20);
        jWinst.setRows(5);
        jWinst.setText("\nJan heeft 10000 \ngewonnen bij dit spel.\n\nJan heeft 10000 \ngewonnen bij dit spel.\n\nJan heeft 10000 \ngewonnen bij dit spel.\n\nJan heeft 10000 \ngewonnen bij dit spel.");
        jWinst.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(jWinst);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 80, 210, 230);

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafisch/images/voices_environmentalist_to_party_main-760x378.jpg"))); // NOI18N
        add(jBackground);
        jBackground.setBounds(0, 0, 580, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestartActionPerformed
        parentFrame.setContentPane(new TeamSpelPanel (parentFrame, namen, leeftijden, record.length, db));
        parentFrame.validate();
    }//GEN-LAST:event_jButtonRestartActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
        db.closeConnection();
    }//GEN-LAST:event_jButtonExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonRestart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jStats;
    private javax.swing.JTextArea jWinnaars;
    private javax.swing.JTextArea jWinst;
    // End of variables declaration//GEN-END:variables
}
